"use client";

import { useActionState } from "react";
import type { DecisionProgressView } from "@/services/decision-progress";
import {
  recordOutcomeAction,
  submitUsefulnessAction,
  transitionActionStatusAction,
  updateActionNoteAction,
  type ProgressActionState,
} from "@/app/decisions/progress-actions";

const initialState: ProgressActionState = { status: "idle", message: "" };
const label = (value: string) => value.replaceAll("_", " ");
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleDateString() : "—";

export function DecisionProgressPanel({
  decisionBriefId,
  progress,
  actionable = true,
}: {
  decisionBriefId: string;
  progress: DecisionProgressView;
  actionable?: boolean;
}) {
  const [feedbackState, feedbackAction, feedbackPending] = useActionState(submitUsefulnessAction, initialState);
  const [transitionState, transitionAction, transitionPending] = useActionState(transitionActionStatusAction, initialState);
  const [noteState, noteAction, notePending] = useActionState(updateActionNoteAction, initialState);
  const [outcomeState, outcomeAction, outcomePending] = useActionState(recordOutcomeAction, initialState);
  const action = progress.action;

  return <section className="brief-section progress-panel">
    <p className="section-label">User-provided workflow · not generated by Gemini</p>
    <h2>Decision Progress</h2>
    <div className="progress-facts">
      <div><span>Usefulness</span><strong>{progress.feedback ? label(progress.feedback.usefulness) : "NOT RATED"}</strong></div>
      <div><span>Action Status</span><strong>{label(progress.actionStatus)}</strong></div>
      <div><span>Started</span><strong>{date(action?.startedAt)}</strong></div>
      <div><span>Completed</span><strong>{date(action?.completedAt)}</strong></div>
      <div><span>Abandoned</span><strong>{date(action?.abandonedAt)}</strong></div>
      <div><span>Outcome</span><strong>{action?.outcome ? label(action.outcome) : "NOT RECORDED"}</strong></div>
    </div>

    <form action={feedbackAction} className="inline-action">
      <input type="hidden" name="decisionBriefId" value={decisionBriefId} />
      <span>Was this Decision Brief useful?</span>
      <button type="submit" name="usefulness" value="USEFUL" disabled={feedbackPending} className={progress.feedback?.usefulness === "USEFUL" ? "selected-action" : ""}>Useful</button>
      <button type="submit" name="usefulness" value="NOT_USEFUL" disabled={feedbackPending} className={progress.feedback?.usefulness === "NOT_USEFUL" ? "selected-action" : "secondary"}>Not Useful</button>
    </form>
    <ActionMessage state={feedbackState} />

    {!actionable && <p className="privacy-note">Action tracking is unavailable because no recommendation was generated from the verified evidence.</p>}
    {actionable && progress.actionStatus === "NOT_STARTED" && <form action={transitionAction} className="progress-form">
      <input type="hidden" name="decisionBriefId" value={decisionBriefId} />
      <input type="hidden" name="status" value="IN_PROGRESS" />
      <label>Action note <textarea name="actionNote" maxLength={500} placeholder="Optional: describe the first practical step." /></label>
      <button type="submit" disabled={transitionPending}>Start Action</button>
    </form>}

    {actionable && progress.actionStatus === "IN_PROGRESS" && <>
      <form action={noteAction} className="progress-form">
        <input type="hidden" name="decisionBriefId" value={decisionBriefId} />
        <label>Action note <textarea name="actionNote" maxLength={500} defaultValue={action?.actionNote ?? ""} /></label>
        <button type="submit" disabled={notePending} className="secondary">Save Note</button>
      </form>
      <div className="progress-actions">
        <form action={transitionAction} className="progress-form">
          <input type="hidden" name="decisionBriefId" value={decisionBriefId} />
          <input type="hidden" name="status" value="COMPLETED" />
          <label>Outcome<select name="outcome" defaultValue="UNKNOWN"><option value="POSITIVE">Positive</option><option value="NEUTRAL">Neutral</option><option value="NEGATIVE">Negative</option><option value="UNKNOWN">Unknown</option></select></label>
          <label>Outcome summary<textarea name="outcomeSummary" maxLength={500} placeholder="Optional: what happened?" /></label>
          <button type="submit" disabled={transitionPending}>Mark as Completed</button>
        </form>
        <form action={transitionAction} className="progress-form">
          <input type="hidden" name="decisionBriefId" value={decisionBriefId} />
          <input type="hidden" name="status" value="ABANDONED" />
          <label>Action note<textarea name="actionNote" maxLength={500} defaultValue={action?.actionNote ?? ""} placeholder="Optional: why was this stopped?" /></label>
          <button type="submit" disabled={transitionPending} className="danger">Abandon Action</button>
        </form>
      </div>
      <ActionMessage state={noteState} />
    </>}

    {actionable && progress.actionStatus === "COMPLETED" && <>
      <p><strong>Outcome summary:</strong> {action?.outcomeSummary ?? "No summary recorded."}</p>
      <form action={outcomeAction} className="progress-form">
        <input type="hidden" name="decisionBriefId" value={decisionBriefId} />
        <label>Outcome<select name="outcome" defaultValue={action?.outcome ?? "UNKNOWN"}><option value="POSITIVE">Positive</option><option value="NEUTRAL">Neutral</option><option value="NEGATIVE">Negative</option><option value="UNKNOWN">Unknown</option></select></label>
        <label>Outcome summary<textarea name="outcomeSummary" maxLength={500} defaultValue={action?.outcomeSummary ?? ""} /></label>
        <button type="submit" disabled={outcomePending} className="secondary">Save Outcome</button>
      </form>
      <form action={transitionAction} className="inline-action">
        <input type="hidden" name="decisionBriefId" value={decisionBriefId} />
        <input type="hidden" name="status" value="IN_PROGRESS" />
        <button type="submit" disabled={transitionPending}>Reopen Action</button>
      </form>
      <ActionMessage state={outcomeState} />
    </>}

    {actionable && progress.actionStatus === "ABANDONED" && <form action={transitionAction} className="progress-form">
      <input type="hidden" name="decisionBriefId" value={decisionBriefId} />
      <input type="hidden" name="status" value="IN_PROGRESS" />
      <label>Action note<textarea name="actionNote" maxLength={500} defaultValue={action?.actionNote ?? ""} /></label>
      <button type="submit" disabled={transitionPending}>Resume Action</button>
    </form>}
    <ActionMessage state={transitionState} />
  </section>;
}

function ActionMessage({ state }: { state: ProgressActionState }) {
  return <div className={`form-status ${state.status}`} role="status" aria-live="polite">{state.message}</div>;
}
