import type { ProcessingRun, RadarItem, ReviewDecision, RssCandidate, RssDiscoveryRun, SourceDefinition, SourceRecord, StoredAnalysis } from "@/domain/schemas";
import type { BusinessProfile, StoredDecisionBrief } from "@/domain/public-mvp";
import type { DecisionAction, DecisionFeedback } from "@/domain/decision-progress";
import type { BillingCustomer, BillingWebhookEvent, CommercialEvent, Entitlement, Subscription, UsageCounter } from "@/domain/billing";

export interface OperatorCounts {
  pendingReviews: number;
  approvedReviews: number;
  rejectedReviews: number;
  publishedItems: number;
  failedRuns: number;
  completedRuns: number;
  totalSources: number;
}

export interface RadarRepository {
  getSourceDefinition(id: string): Promise<SourceDefinition | null>;
  findSourceDefinitionByDomain(domain: string): Promise<SourceDefinition | null>;
  saveSourceDefinition(value: SourceDefinition): Promise<void>;
  listSourceDefinitions(limit?: number): Promise<SourceDefinition[]>;
  countSourceDefinitions(): Promise<number>;
  getRssCandidate(id: string): Promise<RssCandidate | null>;
  findRssCandidateByUrl(normalizedUrl: string): Promise<RssCandidate | null>;
  findRssCandidateByFeedId(sourceDefinitionId: string, feedItemIdHash: string): Promise<RssCandidate | null>;
  saveRssCandidate(value: RssCandidate): Promise<void>;
  listRssCandidates(sourceDefinitionId: string, limit?: number): Promise<RssCandidate[]>;
  saveRssDiscoveryRun(value: RssDiscoveryRun): Promise<void>;
  listRssDiscoveryRuns(sourceDefinitionId?: string, limit?: number): Promise<RssDiscoveryRun[]>;
  findSourceByUrl(normalizedUrl: string): Promise<SourceRecord | null>;
  findSourceByHash(hash: string): Promise<SourceRecord | null>;
  getSource(id: string): Promise<SourceRecord | null>;
  saveSource(value: SourceRecord): Promise<void>;
  listSources(limit?: number): Promise<SourceRecord[]>;
  getRun(id: string): Promise<ProcessingRun | null>;
  saveRun(value: ProcessingRun): Promise<void>;
  listRuns(limit?: number): Promise<ProcessingRun[]>;
  saveAnalysis(value: StoredAnalysis): Promise<void>;
  getAnalysis(id: string): Promise<StoredAnalysis | null>;
  listAnalyses(limit?: number): Promise<StoredAnalysis[]>;
  saveReview(value: ReviewDecision): Promise<void>;
  getReviewForAnalysis(id: string): Promise<ReviewDecision | null>;
  listReviews(limit?: number): Promise<ReviewDecision[]>;
  saveRadarItem(value: RadarItem): Promise<void>;
  getRadarItem(id: string): Promise<RadarItem | null>;
  findRadarItemByAnalysis(id: string): Promise<RadarItem | null>;
  listPublishedItems(limit?: number): Promise<RadarItem[]>;
  saveBusinessProfile(value: BusinessProfile): Promise<void>;
  getBusinessProfile(id: string): Promise<BusinessProfile | null>;
  findBusinessProfileByOwner(ownerId: string): Promise<BusinessProfile | null>;
  listBusinessProfilesByOwner(ownerId: string, limit?: number): Promise<BusinessProfile[]>;
  listAllBusinessProfiles(limit?: number): Promise<BusinessProfile[]>;
  saveDecisionBrief(value: StoredDecisionBrief): Promise<void>;
  getDecisionBrief(id: string): Promise<StoredDecisionBrief | null>;
  listDecisionBriefsByOwner(ownerId: string, limit?: number): Promise<StoredDecisionBrief[]>;
  listAllDecisionBriefs(limit?: number): Promise<StoredDecisionBrief[]>;
  saveDecisionFeedback(value: DecisionFeedback): Promise<void>;
  findDecisionFeedbackByBrief(decisionBriefId: string): Promise<DecisionFeedback | null>;
  listDecisionFeedbackByOwner(ownerId: string, limit?: number): Promise<DecisionFeedback[]>;
  listAllDecisionFeedback(limit?: number): Promise<DecisionFeedback[]>;
  saveDecisionAction(value: DecisionAction): Promise<void>;
  findDecisionActionByBrief(decisionBriefId: string): Promise<DecisionAction | null>;
  listDecisionActionsByOwner(ownerId: string, limit?: number): Promise<DecisionAction[]>;
  listAllDecisionActions(limit?: number): Promise<DecisionAction[]>;
  saveBillingCustomer(value: BillingCustomer): Promise<void>;
  getBillingCustomer(id: string): Promise<BillingCustomer | null>;
  findBillingCustomerByOwner(ownerId: string): Promise<BillingCustomer | null>;
  listAllBillingCustomers(limit?: number): Promise<BillingCustomer[]>;
  saveSubscription(value: Subscription): Promise<void>;
  getSubscriptionByPaddleId(paddleSubscriptionId: string): Promise<Subscription | null>;
  findSubscriptionByOwner(ownerId: string): Promise<Subscription | null>;
  listAllSubscriptions(limit?: number): Promise<Subscription[]>;
  saveEntitlement(value: Entitlement): Promise<void>;
  getEntitlement(ownerId: string): Promise<Entitlement | null>;
  saveUsageCounter(value: UsageCounter): Promise<void>;
  getUsageCounter(ownerId: string, periodKey: string): Promise<UsageCounter | null>;
  listAllUsageCounters(limit?: number): Promise<UsageCounter[]>;
  saveBillingWebhookEvent(value: BillingWebhookEvent): Promise<void>;
  getBillingWebhookEvent(id: string): Promise<BillingWebhookEvent | null>;
  listAllBillingWebhookEvents(limit?: number): Promise<BillingWebhookEvent[]>;
  saveCommercialEvent(value: CommercialEvent): Promise<void>;
  listAllCommercialEvents(limit?: number): Promise<CommercialEvent[]>;
  getOperatorCounts(): Promise<OperatorCounts>;
}
