import { describe, expect, it } from "vitest";
import type { RssCandidate, RssDiscoveryRun, SourceDefinition } from "@/domain/schemas";
import { collectLiveIntelligenceItems, normalizeLiveCandidate, selectEligibleLiveSources } from "@/services/mission-control-live";
import type { RadarRepository } from "@/persistence/repository";
import { MissionControlRequestSchema } from "@/domain/mission-control";

const request = MissionControlRequestSchema.parse({ mode: "live", period: { start: "2026-01-01T00:00:00.000Z", end: "2026-01-31T23:59:59.000Z" } });
const source = (overrides: Partial<SourceDefinition> = {}): SourceDefinition => ({ id: "source-a", displayName: "Alpha Source", publisher: "Alpha", canonicalDomain: "alpha.example", allowedFeedDomains: [], allowedArticleDomains: [], homepage: "https://alpha.example", rssUrl: "https://alpha.example/feed.xml", documentationUrl: null, category: "ai_platform", language: "en", country: "US", trustLevel: "official", status: "enabled", requiresHumanReview: true, notes: "", createdAt: "2026-01-01T00:00:00.000Z", updatedAt: "2026-01-01T00:00:00.000Z", ...overrides });
const candidate = (id: string, sourceDefinitionId = "source-a", overrides: Partial<RssCandidate> = {}): RssCandidate => ({ id, sourceDefinitionId, discoveryRunId: `run-${sourceDefinitionId}`, title: `Live article ${id}`, articleUrl: `https://alpha.example/articles/${id}`, normalizedUrl: `https://alpha.example/articles/${id}`, publishedAt: "2026-01-10T12:00:00.000Z", feedItemIdHash: null, summary: "A real collected summary with sufficient detail for a live item.", publisher: "Alpha", discoveredAt: "2026-01-10T12:00:00.000Z", status: "pending", sourceRecordId: null, processedAt: null, ...overrides });
const run = (sourceDefinitionId: string, status: RssDiscoveryRun["status"] = "success", feedsFailed = 0): RssDiscoveryRun => ({ id: `run-${sourceDefinitionId}`, trigger: "manual", sourceDefinitionId, startedAt: "2026-01-10T12:00:00.000Z", completedAt: "2026-01-10T12:00:01.000Z", status, sourcesConsidered: 1, feedsSucceeded: feedsFailed ? 0 : 1, feedsFailed, itemsExamined: 1, candidatesAccepted: 1, duplicates: 0, skippedItems: 0, validationFailures: 0, errorCategories: [] });

function repository(sources: SourceDefinition[], candidates: Record<string, RssCandidate[]>): RadarRepository {
  return { listSourceDefinitions: async () => sources, listRssCandidates: async (id) => candidates[id] ?? [] } as RadarRepository;
}

describe("Mission Control live collection", () => {
  it("selects only enabled trusted RSS sources in deterministic order", () => { const selected = selectEligibleLiveSources([source({ id: "z", displayName: "Zulu" }), source({ id: "b", displayName: "Beta" }), source({ id: "disabled", status: "disabled" }), source({ id: "blocked", trustLevel: "blocked", status: "blocked" }), source({ id: "no-feed", rssUrl: null })]); expect(selected.map((item) => item.displayName)).toEqual(["Beta", "Zulu"]); });
  it("normalizes live records without fabricating analysis", () => { const item = normalizeLiveCandidate(candidate("one")); expect(item.impactScore).toBe(0); expect(item.confidenceScore).toBe(0); expect(item.evidenceCount).toBe(0); expect(item.verificationStatus).toBe("pending"); expect(item.editorialStatus).toBe("pending"); expect(item.analysisStatus).toBe("deferred"); expect(item.sourceUrl).toContain("articles/one"); expect(item.whyRanked).toBeUndefined(); });
  it("returns deterministic traceable records and collection accounting", async () => { const sources = [source({ id: "source-a", displayName: "Alpha" }), source({ id: "source-b", displayName: "Beta", canonicalDomain: "beta.example", homepage: "https://beta.example", rssUrl: "https://beta.example/feed.xml" })]; const result = await collectLiveIntelligenceItems(repository(sources, { "source-a": [candidate("one")], "source-b": [candidate("two", "source-b", { articleUrl: "https://beta.example/two", normalizedUrl: "https://beta.example/two" })] }), request, { discover: async (_repo, _trigger, id) => run(id ?? ""), now: () => new Date("2026-01-10T12:00:00.000Z") }); expect(result.status).toBe("success"); expect(result.items.map((item) => item.id)).toEqual(["live-one", "live-two"]); expect(result.summary).toMatchObject({ totalRegistrySources: 2, eligibleLiveSources: 2, attemptedSources: 2, successfulSources: 2, failedSources: 0, recordsCollected: 2 }); });
  it("deduplicates records and reports partial failures without hiding usable data", async () => { const sources = [source({ id: "source-a", displayName: "Alpha" }), source({ id: "source-b", displayName: "Beta", canonicalDomain: "beta.example", homepage: "https://beta.example", rssUrl: "https://beta.example/feed.xml" })]; const duplicate = candidate("one", "source-b", { discoveryRunId: "run-source-b", articleUrl: "https://alpha.example/articles/one", normalizedUrl: "https://alpha.example/articles/one" }); const result = await collectLiveIntelligenceItems(repository(sources, { "source-a": [candidate("one")], "source-b": [duplicate] }), request, { discover: async (_repo, _trigger, id) => run(id ?? "", id === "source-b" ? "partial" : "success", id === "source-b" ? 1 : 0) }); expect(result.status).toBe("warning"); expect(result.items).toHaveLength(1); expect(result.summary.duplicateRecords).toBe(1); expect(result.summary.failedSources).toBe(1); });
  it("returns a safe error when every source fails", async () => { const result = await collectLiveIntelligenceItems(repository([source()], { "source-a": [] }), request, { discover: async () => { throw new Error("private failure"); } }); expect(result.status).toBe("error"); expect(result.items).toEqual([]); expect(result.logs.map((entry) => entry.message).join(" ")).not.toContain("private failure"); });
  it("returns a safe warning when no source is eligible", async () => { const result = await collectLiveIntelligenceItems(repository([source({ status: "disabled" })], {}), request); expect(result.status).toBe("warning"); expect(result.summary.eligibleLiveSources).toBe(0); expect(result.items).toEqual([]); });
});
