import { notFound } from "next/navigation";
import { getRepository } from "@/persistence";
import { getReviewDetail } from "@/services/operator-dashboard";
import { logOperatorEvent } from "@/services/operator-events";
import { StatusBadge } from "@/components/operator/status-badge";
import { ReviewActions } from "@/components/operator/review-actions";

export const dynamic = "force-dynamic";

function List({ values, empty = "None identified" }: { values: string[]; empty?: string }) {
  if (!values.length) return <p className="muted">{empty}.</p>;
  return <ul>{values.map((value, index) => <li key={`${value}-${index}`}>{value}</li>)}</ul>;
}

export default async function ReviewDetail({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ result?: string; error?: string }> }) {
  const { id } = await params;
  const query = await searchParams;
  const detail = await getReviewDetail(await getRepository(), id);
  if (!detail) notFound();
  logOperatorEvent({ event: "operator.review_opened", reviewId: detail.review.id, analysisId: detail.analysis.id, sourceId: detail.source.id, runId: detail.run.id, action: "open_review" });
  const analysis = detail.analysis;
  const canDecide = detail.review.status === "pending" || detail.review.status === "needs_changes";
  return <>
    <div className="page-heading"><div><p className="eyebrow">Human Verification evidence</p><h1>{detail.source.title}</h1></div><div className="badge-stack"><StatusBadge value={detail.review.status} /><StatusBadge value={analysis.overallRecommendation} />{detail.radarItem && <StatusBadge value="Decision Brief" />}</div></div>
    {query.result && <p className="success">Human Verification recorded: {query.result}.</p>}
    {query.error && <p className="error">{query.error === "conflict" ? "The verification state changed. Refresh before another action." : "The action was rejected safely. No Decision Brief changed."}</p>}

    <section className="review-section source-facts"><p className="section-label">1 · Trusted Signal evidence</p><dl className="detail-grid">
      <div><dt>Publisher</dt><dd>{detail.source.sourceName}</dd></div><div><dt>Published</dt><dd>{new Date(detail.source.publishedAt).toLocaleString()}</dd></div>
      <div><dt>Canonical source</dt><dd><a href={detail.source.sourceUrl} target="_blank" rel="noopener noreferrer">Open trusted source evidence</a></dd></div><div><dt>Signal source type</dt><dd>{detail.source.sourceType.replaceAll("_", " ")}</dd></div>
    </dl></section>

    <section className="review-section ai-output"><p className="section-label">2 · Gemini Analysis</p><div className="notice">Generated by {detail.run.model}. This is advisory Decision Intelligence for Human Verification; it is not approval, rejection, or publication.</div>
      <h2>Gemini Insight</h2><p>{analysis.summary}</p>
      <h3>Decision-relevant facts</h3><List values={analysis.keyPoints} />
      <h3>Business Impact</h3><p>{analysis.whyItMatters}</p>
      <h3>Recommended Action reasoning</h3><p>{analysis.reasoning}</p>
      <h3>Grounded evidence</h3><ul className="evidence-list">{analysis.evidence.map((entry, index) => <li key={index}><q>{entry.quote}</q><span>{entry.significance}</span></li>)}</ul>
      {analysis.warnings.length > 0 && <><h3>Evidence warnings</h3><List values={analysis.warnings} /></>}
    </section>

    <section className="review-section"><p className="section-label">3 · Decision signals and recommended position</p>
      <div className="score-grid decision-score-grid">
        <div><strong>{analysis.importanceScore}</strong><span>Importance</span></div>
        <div><strong>{analysis.noveltyScore}</strong><span>Novelty</span></div>
        <div><strong>{analysis.confidenceScore}</strong><span>Confidence</span></div>
        <div><strong>{analysis.timelinessScore}</strong><span>Timeliness</span></div>
        <div><strong>{analysis.educationalValueScore}</strong><span>Educational value</span></div>
        <div><strong>{analysis.developerImpactScore}</strong><span>Developer impact</span></div>
        <div><strong>{analysis.enterpriseImpactScore}</strong><span>Enterprise impact</span></div>
        <div><strong>{analysis.researchImpactScore}</strong><span>Research impact</span></div>
        <div><strong>{analysis.relevanceScore}</strong><span>Decision Score</span></div>
      </div>
      <dl className="detail-grid"><div><dt>Recommended position</dt><dd><StatusBadge value={analysis.overallRecommendation} /></dd></div><div><dt>Signal type</dt><dd>{analysis.category.replaceAll("_", " ")}</dd></div></dl>
    </section>

    <section className="review-section recommendation"><p className="section-label">4 · Recommended Action and Business Impact</p>
      <h2>Recommended Action</h2><p>{analysis.recommendedAction}</p>
      <div className="detail-grid"><div><h3>Target audience</h3><List values={analysis.targetAudience} /></div><div><h3>Related topics</h3><List values={analysis.relatedTopics} /></div><div><h3>Potential risks</h3><List values={analysis.potentialRisks} /></div>
        <div><h3>Operational flags</h3><dl><dt>Follow-up recommended</dt><dd>{analysis.followUpRecommended ? "Yes" : "No"}</dd><dt>Urgent Signal</dt><dd>{analysis.breakingNews ? "Yes" : "No"}</dd><dt>Estimated insight reading time</dt><dd>{analysis.estimatedReadingTime} minutes</dd></dl></div></div>
      {analysis.opportunity.isOpportunity && <><h3>Opportunity</h3><dl className="detail-grid"><div><dt>Deadline</dt><dd>{analysis.opportunity.deadline ? new Date(analysis.opportunity.deadline).toLocaleString() : "Not supplied"}</dd></div><div><dt>Eligibility</dt><dd>{analysis.opportunity.eligibility || "Not supplied"}</dd></div><div><dt>Potential benefit</dt><dd>{analysis.opportunity.benefit || "Not supplied"}</dd></div><div><dt>Effort</dt><dd>{analysis.opportunity.effortEstimate || "Not supplied"}</dd></div></dl></>}
    </section>

    <section className="review-section"><p className="section-label">5 · Signal entities</p>
      <div className="entity-grid">{analysis.entities.map((entity, index) => <div className="entity-card" key={`${entity.type}-${entity.normalizedName}-${index}`}><strong>{entity.normalizedName}</strong><span>{entity.type.replaceAll("_", " ")}</span>{entity.name !== entity.normalizedName && <small>Source form: {entity.name}</small>}</div>)}</div>
      {!analysis.entities.length && <p className="muted">No named entities were extracted.</p>}
    </section>

    <section className="review-section duplicate-analysis"><p className="section-label">6 · Signal relationship</p>
      <dl className="detail-grid"><div><dt>Classification</dt><dd><StatusBadge value={analysis.duplicateAnalysis.classification} /></dd></div><div><dt>Similarity score</dt><dd>{analysis.duplicateAnalysis.similarityScore} / 100</dd></div></dl>
      <h3>Reason</h3><p>{analysis.duplicateAnalysis.duplicateReason || "No duplicate relationship was identified."}</p>
      <h3>Related previous signals</h3>
      {analysis.duplicateAnalysis.relatedPreviousArticles.length ? <div className="stack">{analysis.duplicateAnalysis.relatedPreviousArticles.map((article) => <article className="panel compact" key={article.sourceRecordId}><strong>{article.title}</strong><StatusBadge value={article.relation} /><p>{article.reason}</p><small>Evidence record: <code>{article.sourceRecordId}</code></small></article>)}</div> : <p className="muted">No related previous signal was identified.</p>}
      <p className="notice">Signal relationship assessment is advisory. It never verifies, rejects, archives, or publishes a Decision Brief automatically.</p>
    </section>

    <section className="review-section human-decision"><p className="section-label">7 · Human Verification</p><StatusBadge value={detail.review.status} />{detail.review.reviewerNote && <blockquote>{detail.review.reviewerNote}</blockquote>}
      {canDecide ? <ReviewActions analysisId={analysis.id} /> : <p className="muted">This verification is terminal. Duplicate approval is idempotent, but changing an approved or rejected outcome requires a future audited workflow.</p>}
    </section>

    <section className="review-section provenance"><p className="section-label">8 · Provenance and technical evidence</p><dl className="detail-grid">
      <div><dt>Source ID</dt><dd><code>{detail.source.id}</code></dd></div><div><dt>Run ID</dt><dd><code>{detail.run.id}</code></dd></div>
      <div><dt>Gemini Analysis ID</dt><dd><code>{analysis.id}</code></dd></div><div><dt>Human Verification ID</dt><dd><code>{detail.review.id}</code></dd></div>
      <div><dt>Decision Brief</dt><dd><code>{detail.radarItem?.id || "Not available"}</code></dd></div><div><dt>Processing mode</dt><dd>{detail.processingMode}</dd></div>
      <div><dt>Processed</dt><dd>{new Date(analysis.createdAt).toLocaleString()}</dd></div><div><dt>Prompt version</dt><dd>{detail.run.promptVersion}</dd></div>
      <div><dt>Schema validation</dt><dd>{detail.run.validationOutcome}</dd></div><div><dt>Decision Brief state</dt><dd>{detail.radarItem?.publicationState || "not available"}</dd></div>
    </dl></section>
  </>;
}
