import { notFound } from "next/navigation";
import { getAnonymousSessionId } from "@/auth/anonymous-session";
import { getRepository } from "@/persistence";
import { getOwnedDecisionBrief } from "@/services/public-mvp";
import { getDecisionProgress } from "@/services/decision-progress";
import { DecisionProgressPanel } from "@/components/public/decision-progress-panel";

export const dynamic = "force-dynamic";

const label = (value: string) => value.replaceAll("_", " ");

export default async function DecisionBriefPage({ params }: { params: Promise<{ id: string }> }) {
  const ownerId = await getAnonymousSessionId();
  if (!ownerId) notFound();
  const repository = await getRepository();
  const brief = await getOwnedDecisionBrief(repository, ownerId, (await params).id);
  if (!brief) notFound();
  const progress = await getDecisionProgress(repository, ownerId, brief.id);

  const context = brief.businessContextSnapshot;
  if (brief.result.status === "INSUFFICIENT_EVIDENCE") return <section className="public-shell">
    <p className="eyebrow">Decision Brief · {brief.businessName}</p>
    <h1>{brief.signalSnapshot.title}</h1>
    <div className="insufficient-panel"><span className="decision-badge">INSUFFICIENT EVIDENCE</span><h2>No recommendation was generated.</h2><p>{brief.result.reason}</p><h3>Evidence still needed</h3><ul>{brief.result.missingEvidence.map((item) => <li key={item}>{item}</li>)}</ul></div>
    <p className="privacy-note">The engine stopped at {label(brief.result.stage).toLowerCase()} instead of guessing.</p>
    <DecisionProgressPanel decisionBriefId={brief.id} progress={progress} actionable={false} />
  </section>;

  const decision = brief.result.decisionBrief;
  const score = decision.score;
  return <section className="public-shell decision-page">
    <header className="decision-header">
      <div><p className="eyebrow">Personalized Decision Brief</p><h1>{decision.decisionQuestion}</h1><p>{brief.signalSnapshot.title}</p></div>
      <div className="score-card"><span className="decision-badge">{label(decision.recommendedPosition)}</span><strong>{score.decisionScore}</strong><small>Decision Score</small><span>Confidence {decision.confidence}/100</span></div>
    </header>

    <section className="brief-section"><h2>Business Context</h2><dl className="context-grid"><div><dt>Business</dt><dd>{brief.businessName}</dd></div><div><dt>Industry</dt><dd>{context.industry}</dd></div><div><dt>Company Size</dt><dd>{label(context.companySize)}</dd></div><div><dt>Primary Goal</dt><dd>{context.businessGoals[0]}</dd></div><div><dt>AI Maturity</dt><dd>{label(context.aiMaturity)}</dd></div><div><dt>Risk Tolerance</dt><dd>{label(context.riskTolerance)}</dd></div></dl></section>

    <section className="brief-section"><p className="section-label">Generated business analysis</p><h2>Decision Intelligence</h2>
      <h3>Gemini Insight</h3>{decision.geminiInsight.map((claim) => <p key={claim.text}>{claim.text} <EvidenceRefs ids={claim.evidenceIds} /></p>)}
      <h3>Business Impact</h3>{decision.businessImpact.map((claim) => <p key={claim.text}>{claim.text} <EvidenceRefs ids={claim.evidenceIds} /></p>)}
      <h3>Recommended Position</h3><p><span className="decision-badge">{label(decision.recommendedPosition)}</span></p>
      <h3>Recommended Action</h3><p>{decision.recommendedAction} <EvidenceRefs ids={decision.recommendationEvidenceIds} /></p>
    </section>

    <section className="brief-section"><h2>Available Options</h2><div className="option-grid">{decision.availableOptions.map((option) => <article className="panel" key={option.position}><h3>{label(option.position)}</h3><p>{option.description} <EvidenceRefs ids={option.supportingEvidenceIds} /></p></article>)}</div></section>
    <section className="brief-section two-column"><div><h2>Expected Benefits</h2><ul>{decision.expectedBenefits.map((claim) => <li key={claim.text}>{claim.text} <EvidenceRefs ids={claim.evidenceIds} /></li>)}</ul></div><div><h2>Potential Risks</h2><ul>{decision.potentialRisks.map((claim) => <li key={claim.text}>{claim.text} <EvidenceRefs ids={claim.evidenceIds} /></li>)}</ul></div></section>
    <section className="brief-section"><h2>Estimated Effort</h2><p><strong>{decision.estimatedEffort.level}</strong> — {decision.estimatedEffort.rationale} <EvidenceRefs ids={decision.estimatedEffort.supportingEvidenceIds} /></p></section>

    <section className="brief-section"><p className="section-label">Application-calculated · not generated by Gemini</p><h2>Explainable Decision Score</h2><div className="score-components"><Score label="Signal Importance" value={score.signalImportance} /><Score label="Evidence Confidence" value={score.evidenceConfidence} /><Score label="Business Applicability" value={score.businessApplicability} /><Score label="Urgency" value={score.urgency} /><Score label="Expected Impact" value={score.expectedImpact} /><Score label="Final Decision Score" value={score.decisionScore} /></div></section>

    <section className="brief-section evidence-section"><p className="section-label">Verified facts</p><h2>Evidence</h2><p>Source: <a href={brief.signalSnapshot.sourceUrl} target="_blank" rel="noopener noreferrer">{brief.signalSnapshot.title} — {brief.signalSnapshot.sourceName}</a> · Published {new Date(brief.signalSnapshot.publishedAt).toLocaleDateString()}</p>{decision.supportingEvidence.map((evidence) => <blockquote id={`evidence-${evidence.id}`} key={evidence.id}><strong>{evidence.id}</strong> “{evidence.quote}”<footer>{evidence.significance}</footer></blockquote>)}</section>
    <section className="brief-section two-column"><div><h2>Success Criteria</h2><ul>{decision.successCriteria.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h2>Reconsideration Triggers</h2><ul>{decision.reconsiderationTriggers.map((item) => <li key={item}>{item}</li>)}</ul></div></section>
    <DecisionProgressPanel decisionBriefId={brief.id} progress={progress} />
  </section>;
}

function EvidenceRefs({ ids }: { ids: string[] }) {
  return <small className="evidence-refs">Evidence: {ids.map((id) => <a href={`#evidence-${id}`} key={id}>[{id}]</a>)}</small>;
}

function Score({ label: name, value }: { label: string; value: number }) {
  return <div><span>{name}</span><strong>{value}</strong><small>/100</small></div>;
}
